language: objective-c
before_install:
  - brew update
install:
  - brew tap larsimmisch/avr
  - brew install avr-binutils
  - brew install gmp
  - brew install libmpc
  - brew install mpfr
  - ruby .wrap.rb brew install avr-gcc
  - brew install dfu-programmer
script: make